[project]
name = "work"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "zyt", email = "zhangyongtianaa@sina.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "pymongo>=4.17.0",
    "python-dotenv>=1.2.2",
]

[project.scripts]
work = "work:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
